# Do not edit this file - Generated by Perlito 6.0
use v5;
use utf8;
use strict;
use warnings;
no warnings ('redefine', 'once', 'void', 'uninitialized', 'misc', 'recursion');
use Perlito::Perl5::Runtime;
our $MATCH = Perlito::Match->new();
{
package GLOBAL;
sub new { shift; bless { @_ }, "GLOBAL" }

# use v6 
;
{
package Perlito::Go::Channel;
sub new { shift; bless { @_ }, "Perlito::Go::Channel" }
sub push { my $self = $_[0]; die('TODO') };
sub shift { my $self = $_[0]; die('TODO') }
}


}

1;
